#!/bin/bash

usage() {
    echo "        feature: create feature branch (start to develop)"
    echo "        hotfix: create hotfix branch (start to master)"
    echo "        bugfix: create bugfix branch (start to feature)"
    echo "        release: create a release branch (start to develop)"
    echo "        commit: commit all change with standard commit message"
    echo "        finish: feature/bugfix merge to develop, hotfix merge to master and develop. delete local and remote current branch after merge"
    echo "        publish: push current branch to remote (crete a remote branch if not exist)"
    echo "        delete: delete a current branch with git flow"
    exit
}
if [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]  || [[ -z "$1" ]]; then
    usage
fi

prev=""
consoleTaskId=""
nextRevision="minor"

if [[ "$1" == "init" ]]; then
    git flow init -d
fi

for var in "$@"
do
    if [[ "$prev" == "-t" ]]; then
        consoleTaskId="$var"
    fi
    if [[ "$var" == "-m" ]]; then
        nextRevision="major"
    fi
    prev="$var"
done

case "$1" in
    feature | bugfix)
        git-standard-feature-and-bugfix "$1" "$consoleTaskId"
        ;;
    hotfix)
        git flow "$1" start "$(git-standard-get-next-version patch)"
        ;;
    release)
        git flow release start "$(git-standard-get-next-version ${nextRevision})"
        ;;
    finish | publish)
        git flow "$(git-standard-get-actual-branch-type)" "$1" "$(git-standard-get-actual-branch-name)"
        ;;
    commit)
        git-standard-save "$(git-standard-get-actual-branch-type)" "$(git-standard-get-actual-branch-name)"
        ;;
    *)
        git flow "$@"
esac

