#!/bin/bash

name="$2"
if [[ "$name" == '' ]]; then
    printf "feature name: "
    read -r name
fi
newName="${name// /-}"
if [[ "$taskId" != "" ]]; then
    branchName="#$taskId-$newName"
else
    branchName="$newName"
fi
git flow "$1" start "$branchName"
